config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lists do
    resources :tasks
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :tasks, dependent: :destroy
  validates :name, uniqueness: true, presence: true,
                                    length: {minimum: 4}

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :name, uniqueness: true, presence: true,
                                    length: {minimum: 4}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @tasks = @list.tasks.all
    @task = @list.tasks.build
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "Successfully created!"
      redirect_to lists_path
    else
      @lists = List.all
      render :index
    end
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
  end

  def create
    @list = List.find(params[:list_id])
    @tasks = @list.tasks.all
    @task = @list.tasks.create(task_params)
    if @task.save
      flash[:notice] = "Task successfully created"
      redirect_to list_path(@list)
    else
      flash[:alert] = "Error! Could not be saved"

      render 'lists/show'
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = Task.destroy(params[:id])
    redirect_to list_path(@list)
  end

  def edit
    @list = List.find(params[:list_id])
    # @task = Task.find(params[:id])
    @task = @list.tasks.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to list_path(@list)
    end
  end

  private
  def task_params
    params.require(:task).permit(:name, :descriptions, :status, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/your_model_name_in_plural_helper.rb
module YourModelNameInPluralHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
<script src="https://use.fontawesome.com/10f489fef6.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
<script src="js/app.js"></script>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

app/views/lists/edit.html.erb
<div class="jumbotron">
<div class="formwidth">
<div class="text-center lead"><h3><a1> EDIT BOOK NAME </a1></div>

<CENTER>
<%= simple_form_for @list do |f| %>
<%= f.input :name, label: '-' %>
<%= f.button :submit %>
</center>

<% end %>

<br>
<div class="text-center lead"><H3><%= link_to 'BACK HOME', lists_path %></H3></div>
</div>
</div>

app/views/lists/index.html.erb
<div class="center formsize">
  <%= simple_form_for @list do |f| %>
  <%= f.input :name, label: 'Category Name:', :label_html => { :class => 'formfont' } %>
  <%= f.button :submit, "Create List" %>
  <% end %>
</div>
<br>
<table>
  <tbody>
    <% @lists.each do |list| %>
    <center>
      <div class="card cardcolour" style="width: 30rem; height: 10rem;">
        <div class="card-body">
          <h4 class="card-title cardfont">
            <%= link_to list.name, list_path(list)%>
          </h4>
          <br>
          <h6 class="card-subtitle mb-2 text-muted" >
            <%= link_to 'Edit', edit_list_path(list), { class: "badge badge-light" } %>
            <%= link_to 'Delete', list_path(list), method: :delete, data: { confirm: 'Are you sure?' },  class: "badge badge-light"%>
          </h6>
        </div>
      </div>
    </center>
    <br>
    <% end %>
</tbody>
</table>
<br>

app/views/lists/new.html.erb
<h1>Lists#new</h1>
<p>Find me in app/views/lists/new.html.erb</p>

<h1>Task Lists</h1>

<%= simple_form_for @list do |f| %>
<%= f.input :name, label: 'Name' %><br>
<%= f.input :total, label: 'Total' %><br>
<%= f.button :submit %>

<% end %>

app/views/lists/show.html.erb
<div class ="jumbotron jumbocolor">
<center>
  <h1 class="display-3 jumbocolor">
  <div class="formcolor">
    <a1>Category: <%= @list.name %></a1><br>
  </h1><br>
  <p class="lead">Tasks<p>
</div>

</center>
</div>
</div>

<div class="container-fluid mx-auto">
<div class="col-md-6 col-md-offset-3 mx-auto">
<% @tasks.each do |task| %>

<div class="row task">

<div class="col-md-8">
  <h2 style="opacity: 1;" class="title"><b><%= task.name %></b></h2>
  <p style="opacity: 0.8" class="task-description task-sub-title"><%= task.descriptions %></p>
  <p style="opacity: 0.5;" class="time-ago task-sub-title">Due: <%= task.date %></p>
</div>

<div class="col-md-2">
<b><%= task.status%></b>
</div>

<div class="col-md-1">
  <p><%= link_to 'Edit', edit_list_task_path(@list,task), { class: "badge badge-light" } %></p>

</div>

<div class="col-md-1">
<p><%= link_to '<i class="fa fa-lg fa-trash"></i>'.html_safe, list_task_path(@list,task), method: :delete, data: { confirm: 'Are you sure?' },  class: "badge badge-light" %></p>
<br>
</div>

</div>
<br>
<% end %>
</div>
</div>


  <div class="jumbotron jumbotron-fluid">
  <div class="container">
  <div class = "formwidth">
<div class=" text-center title"><h2><b>Add Task</b></h2></div>
<%= simple_form_for [@list, @task] do |f| %>
<%= f.input :name, label: 'Name:' %><br>
<%= f.input :descriptions, label: 'Description:' %><br>
<%= f.label :status, label: 'Status:' %><br>
<%= f.collection_radio_buttons :status, [['INCOMPLETE', 'Incomplete'] ,['IN PROGRESS', 'In Progress'], ['COMPLETED', 'Completed']], :first, :last %><br><br>
<%= f.input :date, label: 'Due:' %>
<div class="text-center"><%= f.button :submit %></div>
<% end %>



<br><br><br>
</div>
<div class="text-center lead"><h3><%= link_to 'BACK HOME', lists_path %></h3></p>
</div>

app/views/lists/update.html.erb
<h1>Lists#update</h1>
<p>Find me in app/views/lists/update.html.erb</p>

app/views/tasks/edit.html.erb
<div class="jumbotron">
<div class="formwidth">
<div class="text-center lead"><h3><a1> EDIT TASK NAME </a1></div>


<%= simple_form_for [@list, @task] do |f| %>
<%= f.input :name, label: 'Name' %><br>
<%= f.input :descriptions, label: 'Description' %><br>
<%= f.collection_radio_buttons :status, [['INCOMPLETE', 'Incomplete'] ,['IN PROGRESS', 'In Progress'], ['COMPLETED', 'Completed']], :first, :last %><br>
<%= f.input :date, label: 'Due' %><br>

<%= f.button :submit %>
<% end %>

<br>
<div class="text-center lead"><H3><%= link_to 'BACK HOME', lists_path %></H3></div>
</div>
</DIV>